### ISSUE TITLE
使用不同大小的图片测试，480p及以上会崩溃

### ISSUE THREAD

**Issue by Protears** [ViewFaceCore/ViewFaceCore#14]
测试代码：https://gitee.com/Protear/face-detection-console

托管调试助手 "FatalExecutionEngineError":“运行时遇到了错误。此错误的地址为 0x2f767932，在线程 0x1ba0 上。错误代码为 0xc0000005。此错误可能是 CLR 中的 bug，或者是用户代码的不安全部分或不可验证部分中的 bug。此 bug 的常见来源包括用户对 COM-interop 或 PInvoke 的封送处理错误，这些错误可能会损坏堆栈。”

**Comment by Protears** [comment]
![image](https://user-images.githubusercontent.com/45806588/103275399-0c7def00-49ff-11eb-8176-944437808abe.png)

循环检测480p图片时调试输出如上图所示

**Comment by View12138** [comment]
因为之前 PInvoke 的方式可能存在部分问题，请等待下个版本修复。

**Comment by Protears** [comment]
> 因为之前PInvoke的方式可能存在部分问题，请等待下一个版本修复。

好的，期待新版本的更新

**Comment by Joe1130** [comment]
大佬，新版本什么时候出啊
(；へ：)

**Comment by View12138** [comment]
可以更新到 ViewFaceCore 0.3.5
