### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by 51zhaoshi** [ViewFaceCore/ViewFaceCore#15]
1.多次调用ViewFace.FaceDetectorAsync方法后，有时vs会报这个错误。程序会停止
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”
2.这是控制台的日志信息。
Fatal error. System.AccessViolationException: Attempted to read or write protect
ed memory. This is often an indication that other memory is corrupt.
   at ViewFaceCore.Plus.Platform.ViewFacePlus64.ViewDispose()
   at ViewFaceCore.Plus.Platform.ViewFacePlus64.ViewDispose()
   at ViewFaceCore.Plus.ViewFacePlus.ViewDispose()
   at ViewFaceCore.Sharp.ViewFace.Finalize()

**Comment by View12138** [comment]
因为之前 PInvoke 的方式可能存在部分问题，请等待下个版本修复。

**Comment by 51zhaoshi** [comment]
非常感谢，期待下个版本早点出来。

**Comment by View12138** [comment]
可以更新到 ViewFaceCore 0.3.5
