### ISSUE TITLE
ViewFaceTest里写了一个循环，连接执行几次报：Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by elanyang** [ViewFaceCore/ViewFaceCore#21]
![image](https://user-images.githubusercontent.com/4235859/115346313-9c2fef00-a1e2-11eb-8efb-b26815c66ee4.png)

**Comment by elanyang** [comment]
asp.net core会报错，.net framework是稳定的。

**Comment by View12138** [comment]
> asp.net core会报错，.net framework是稳定的。

这个目前不清楚原因 ^_^ 那麻烦先使用 .net fx , 我再排查看看

**Comment by asdRain** [comment]
> > asp.net core会报错，.net framework是稳定的。
> 
> 这个目前不清楚原因 ^_^ 那麻烦先使用 .net fx , 我再排查看看

请问排查到原因了吗？

**Comment by View12138** [comment]
更新到 ViewFaceCore 0.3.5

**Comment by ZhouBoAdmin** [comment]
更新到0.3.5这个问题还是存在
