### ISSUE TITLE
是否支持Linux？

### ISSUE THREAD

**Issue by asdRain** [ViewFaceCore/ViewFaceCore#25]

**Comment by View12138** [comment]
test/linux 分支上有 @withsalt 提交的对 linux 的支持, 但是目前还没有做测试

**Comment by withsalt** [comment]
作者你写了Linux的ViewFace的库吗？我提交的分支里面没有包含Linux的库，所以不支持Linux，只是一种支持Linux的思路。我不会C++[苦笑]。

**Comment by View12138** [comment]
@withsalt 啊这，我现在明白你意思了。😅
那我还没开始写呢 [刚刚换了工作，还没时间]

**Comment by withsalt** [comment]
:+1::+1::+1:哈哈，等你哦~

**Comment by View12138** [comment]
@withsalt 今天已经更新了支持 linux , 但是目前发现 设置 LD_LIBRARY_PATH 环境变量的方式并不能查找到 *.so，把相关的lib拷贝到 /usr/lib/ 下就可以正常访问了。请问你还有解决方案吗？

**Comment by View12138** [comment]
@withsalt 你好，如果需要在本地调试的话，可以按照以下方法构建。(我本地是使用 WSL 来调试 Linux 版本，不知道是否会有影响)
- nuget 中已发布 0.3.5-alpha2 版本可以测试。
- 现在也可以拉去源代码以及所有子模块，从 SeetaFace 开始完全自行构建。
- 或者将 SeetaFace 官方提供的包 拷贝至 (windows)[ViewFaceCore\SeetaFace\index\build\bin\x64\*.dll/ViewFaceCore\SeetaFace\index\build\bin\x86\*.dll] / (Linux)[ViewFaceCore\SeetaFace\index\build\lib64\*.so]，然后开始构建
  1. Linux\ViewFaceBridge x64
  2. Windows\ViewFaceBridge x64
  3. Windows\ViewFaceBridge x86
  4. ViewFaceCore AnyCPU

**Comment by withsalt** [comment]
@View12138 感谢大佬！我试试。

**Comment by withsalt** [comment]
你好，我也在Linux中测试了，发现设置 LD_LIBRARY_PATH 确实不能查找到相关的动态库。
但是我手动将*.so文件复制至/use/lib，依旧没有找到相关的动态库。

![](https://imgur.com/0SwaEnP)

**Comment by withsalt** [comment]
你好，我已经在Linux下成功允许ConcoleSimple，但是确实 设置 LD_LIBRARY_PATH 环境变量的方式并不能查找到 *.so。我研究下有没有相应的解决办法。

**Comment by withsalt** [comment]
目前找到的资料来看 设置 LD_LIBRARY_PATH 环境变量的方式行不通，LD_LIBRARY_PATH 必须在应用程序启动之前设置。具体情况可以查看：https://github.com/dotnet/runtime/issues/34711
我在尝试通过NativeLibrary的方式，目前遇到的问题是：

```
System.DllNotFoundException: Unable to load shared library '/home/deepin/Projects/ViewFaceCore/Simples/ConsoleSimple/bin/Debug/net6.0/libViewFaceBridge.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSeetaAgePredictor600.so: cannot open shared object file: No such file or directory
```

加载不了相关的依赖项。

我q：NzcwNzAyODI3。或许可以聊聊？

**Comment by withsalt** [comment]
已经解决在Linux下查找 *.so的问题。
我简单测试之后，在Windows和Linux都能使用这种方式来加载依赖。代码在ViewFacePlus.cs中，因为我没法编译C++项目，改了项目配置，所以我就不提pull request了。可以在我fork的项目中查看。

**Comment by View12138** [comment]
@asdRain 现已支持 Linux，更新到 ViewFaceCore 0.3.5
