### ISSUE TITLE
IIS部署会出现Unable to load DLL 'FaceLibraries\x64\ViewFace.dll' or one of its dependencies: 拒绝访问的异常

### ISSUE THREAD

**Issue by Alvin4550** [ViewFaceCore/ViewFaceCore#28]
IIS7 部署会出现Unable to load DLL 'FaceLibraries\x64\ViewFace.dll' or one of its dependencies: 拒绝访问的异常。用的 .net core 3.1

**Comment by View12138** [comment]
请确保安装了 VC++ 运行库

**Comment by ffufeng** [comment]
请问这个VC++运行库是什么版本，客户端系统是Win7

**Comment by withsalt** [comment]
已处理
