### ISSUE TITLE
调Extract方法，报错 System.OverflowException:“算术运算导致溢出

### ISSUE THREAD

**Issue by zazzlec** [ViewFaceCore/ViewFaceCore#31]
var infos = ViewFace.FaceTrack(bitmap1); // 识别画面中的人脸
            foreach (var info in infos)
            {
                ViewFaceCore.Sharp.Model.FaceMarkPoint[] pp = ViewFace.FaceMark(bitmap1, new ViewFaceCore.Sharp.Model.FaceInfo() { Location = info.Location, Score = info.Score  });
                float[] f= ViewFace.Extract(bitmap1,  pp);

            }

**Comment by View12138** [comment]
更新到 ViewFaceCore 0.3.5
