### ISSUE TITLE
Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by wu-xiaohua** [ViewFaceCore/ViewFaceCore#33]
这个错误无解啊，识别个几张就会出现

**Comment by View12138** [comment]
@wu-xiaohua 使用的是哪个版本？

**Comment by jyk1987** [comment]
使用的时0.3.5，我也是遇到这个问题，就是实例代码循环运行几次就出现这个了。

**Comment by jyk1987** [comment]
> 

使用的时0.3.5，我也是遇到这个问题，就是实例代码循环运行几次就出现这个了。

**Comment by jyk1987** [comment]
> @wu-xiaohua 使用的是哪个版本？

使用的时0.3.5，我也是遇到这个问题，就是实例代码循环运行几次就出现这个了。

**Comment by jyk1987** [comment]
刚才试了一下，0.3.4也是有同样的问题。

**Comment by jyk1987** [comment]
做了一下测试，如果使用完整的实例循环测试几次就出错了。
但是如果注掉里面的质量评估和活体检测就可以顺利循化测试。
但是如果将ViewFace声明在循环外面，测试循环跑几圈后人脸追踪也会出错。
目前能仅使用一个ViewFace对象进行反复使用的仅为人脸识别和相似度对比。

**Comment by View12138** [comment]
@jyk1987 如果使用的是 0.3.5 的话，有没有使用 using？
```csharp
using var viewFace = new ViewFace();
```

**Comment by wu-xiaohua** [comment]
> @jyk1987如果使用的是0.3.5的话，有没有使用使用？
> 
> ```cs
> 使用 var  viewFace  =  new  ViewFace ();
> ```

后面我调用了Dispose(),同样会有这个错误

**Comment by huaxuanHan** [comment]
同样的问题，识别几张就出错了

**Comment by ZhouBoAdmin** [comment]
请问这个问题怎么解决

**Comment by 13814861294** [comment]
> 请问这个问题怎么解决

不管是.Net FrameWork还是.Net Core,将程序调整成x86就可以解决这个问题

**Comment by zshuaig666** [comment]
> > 请问这个问题怎么解决
> 
> 不管是.Net FrameWork还是.Net Core,将程序调整成x86就可以解决这个问题

改成x86确实可以，但还有设么办法能在x64运行吗

**Comment by Aaron701** [comment]
> > > 请问这个问题怎么解决
> > 
> > 
> > 不管是.Net FrameWork还是.Net Core,将程序调整成x86就可以解决这个问题
> 
> 改成x86确实可以，但还有设么办法能在x64运行吗

如果项目很大，大项目又必须使用x64，可以将人脸识别分离成一个独立的x86项目模块,可以用Windows服务或者linux服务承载，其他需要使用的地方可以使用RPC等方式进行调用，按照现在的硬件配置，基本不会影响性能。
注意一定要切换成X86，不能是Any CPU，之前有回答说.Net FrameWork下可以是因为选则的是Any CPU，这样虽然有时候是可以正常运行，但是还是会有不稳定的情况(有时候会在x64运行，就会报错)
这只是暂时的处理办法，最根源还是要从源码上进行处理。

**Comment by asdRain** [comment]
> 

请问这个说的源码上面处理，指的是SeetaFace的Code，还是当前的ViewFaceCore?

**Comment by View12138** [comment]
@asdRain 应该是 ViewFaceCore 的 Bridge 层的bug

**Comment by asdRain** [comment]
> @asdRain 应该是 ViewFaceCore 的 Bridge 层的bug

大佬求修复

**Comment by View12138** [comment]
急用的话还是把人脸识别这个模块单独拆出来用x86吧，最近一直都挺忙，没时间搞这个项目 ! >_<

**Comment by withsalt** [comment]
已处理

**Comment by Aaron701** [comment]
x86也可以在x64上面运行呀？



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 8, 2022 18:15 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ViewFaceCore/ViewFaceCore] Fatal error. Internal CLR error.(0x80131506) (Issue #33)




   
请问这个问题怎么解决
  
不管是.Net FrameWork还是.Net Core,将程序调整成x86就可以解决这个问题
  
改成x86确实可以，但还有设么办法能在x64运行吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
