### ISSUE TITLE
建议移除对System.Drawing.Common的依赖

### ISSUE THREAD

**Issue by zhouqime** [ViewFaceCore/ViewFaceCore#34]
.net 6发布后[微软移除了非Windows平台System.Drawing.Common模块的支持](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)，继续使用Bitmap作为接口会导致在linux上无法使用这个库。
事实上Bitmap仅仅只是读取图像信息，这一步很多库都可以做到，比如Silk.Net（opencv），SkiaSharp（skia），不如内置一个ImageInfo,包含width\height\channels\data信息，作为参数，至于用户爱用Bitmap生成这个ImageInfo，还是爱用其他库，随用户自己。

**Comment by View12138** [comment]
@zhouqime 谢谢你的建议，在后续版本将考虑 .net6 及以上采用这种方式，而 .net5 及以下将继续保持对 System.Drawing.Common 的依赖。

**Comment by withsalt** [comment]
已经拆分System.Drawing.Common和ViewFaceCore，可自行选择使用的图形库，支持ImageSharp、SkiaSharp、System.Drawing
