### ISSUE TITLE
放到服务器上面，提示找不到ViewFaceBridge.dll

### ISSUE THREAD

**Issue by huaxuanHan** [ViewFaceCore/ViewFaceCore#35]
System.DllNotFoundException:“无法加载 DLL“ViewFaceBridge”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。”

**Comment by withsalt** [comment]
服务器系统是啥？

**Comment by huaxuanHan** [comment]
服务器是server2022，两台服务器都不行，另外同事的两台win10 电脑也不行，好像我周围出了我的电脑可以，别的机器都会提示缺少这个dll文件，我用一台笔记本重装了系统，安装了运行库，安装了VS2022，别的什么都没装，新建项目把示例代码直接放进去还是提示缺少这个dll文件，不知道啥情况，在bin里面生成的viewfacecore文件夹里面有这个dll文件的

**Comment by huaxuanHan** [comment]
说错了，服务器是server2012，我在自己的测试服务器server2022上面试的也不行，还是提示缺少这个dll，目前测试了server2012、2022三台服务器都缺少dll文件，三个win10 笔记本，其中我的笔记本没问题，能运行起来，另两台都提示缺少dll文件

**Comment by withsalt** [comment]
尝试安装运行时：ViewFaceCore.runtime.win.vc

**Comment by huaxuanHan** [comment]
感谢，安装上这个运行时可以了

**Comment by huaxuanHan** [comment]
感谢，安装上这个运行时可以了
