### ISSUE TITLE
初始化ViewFaceCore出现The type initializer for 'ViewFaceCore.Plus.ViewFaceBridge' threw an exception这个异常,版本是0.3.5,请问怎么解决

### ISSUE THREAD

**Issue by ZhouBoAdmin** [ViewFaceCore/ViewFaceCore#37]

**Comment by share36** [comment]
我也遇到同样的问题，后来查看文件依赖关系，发现是少VC运行库，MSVCP140D.dll、VCRUNTIME140D.dll、VCRUNTIME140_1D.dll、ucrtbased.dll。
折腾了一下，找到了对应版本的ucrtbased.dll和VCRUNTIME140_1D.dll，其它两个文件用任何版本都不能正常加载。
从依赖的dll文件名这些链接库是Debug版本应该。

**Comment by Xiaobaiaixiaobai** [comment]
问下，这个问题最后怎么解决呢？c++运行库也装了
![QQ图片20220604223709](https://user-images.githubusercontent.com/35687605/172007478-2eaf0652-ff68-4f46-93ba-1a8c45f73d67.png)
