### ISSUE TITLE
Can not use this repo in .NET 6.0 X64 for Window 10

### ISSUE THREAD

**Issue by zydjohnHotmail** [ViewFaceCore/ViewFaceCore#38]
Hello:
I found this repo, it seems to be a good software.  I want to do some testing.
I have create one Windows Forms App targeting .NET 6.0 (CPU: x64, but x86 has the same error)
I installed latest version of Nuget:
PM> Install-Package ViewFaceCore -Version 0.3.5
The following is my C# code:

using System;
using System.Drawing;
using ViewFaceCore.Sharp;

namespace ViewFaceCoreFaceDetectForm
{
    public partial class Form1 : Form
    {
        public const string Face1_JPG_File = @"D:\Images\Temp\1.jpg";

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            ViewFace face = new();
            Bitmap bitmap = (Bitmap)Image.FromFile(Face1_JPG_File);
            var infos = face.FaceDetector(bitmap);
            Console.WriteLine($"Face # detected {infos.Length}");
            Console.WriteLine($"Score and Position");
            for (int i = 0; i < infos.Length; i++)
            {
                Console.WriteLine($"{i}\t{infos[i].Score:f8}\t{infos[i].Location}");
            }
            Console.Read();
        }
    }
}

But when I run this, I got error:
Inner Exception 1:
DirectoryNotFoundException: 找不到本机库目录: C:\SoccerVideos\Images\ViewFaceCoreFaceDetectForm\ViewFaceCoreFaceDetectForm\bin\Debug\net6.0-windows10.0.19041.0\viewfacecore\win\x64

I also download the repo source code (ViewFaceCore-main), and try to build it in Visual Studio 2022 (Version 17.1.1). I am using Windows 10 (Version 21H2, OS build 19044.1586)
But I also got some errors, like the following:
Error	MSB8020	The build tools for Remote_GCC_1_0 (Platform Toolset = 'Remote_GCC_1_0') cannot be found. To build using the Remote_GCC_1_0 build tools, please install Remote_GCC_1_0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".	

Error	C1083	Cannot open include file: 'seeta/FaceDetector.h': No such file or directory

Let me know how to fix this issue.
PS: You can reply in Chinese, if not easy to reply in English.
I think if I can install NUGET package, all necessary libraries should be OK, there should be no more errors.  By the way, if there is any library which is only available in Baidu Pan, then all the people outside China can’t access.
Thanks,

**Comment by Aaron701** [comment]
You need to use nuget to install ViewFaceCore.runtime.win.vc and ViewFaceCore.all_models, and it can only run on X86, it is not stable under X64

**Comment by Aaron701** [comment]
> Hello: I found this repo, it seems to be a good software. I want to do some testing. I have create one Windows Forms App targeting .NET 6.0 (CPU: x64, but x86 has the same error) I installed latest version of Nuget: PM> Install-Package ViewFaceCore -Version 0.3.5 The following is my C# code:
> 
> using System; using System.Drawing; using ViewFaceCore.Sharp;
> 
> namespace ViewFaceCoreFaceDetectForm { public partial class Form1 : Form { public const string Face1_JPG_File = @"D:\Images\Temp\1.jpg";
> 
> ```
>     public Form1()
>     {
>         InitializeComponent();
>     }
> 
>     private void Form1_Load(object sender, EventArgs e)
>     {
>         ViewFace face = new();
>         Bitmap bitmap = (Bitmap)Image.FromFile(Face1_JPG_File);
>         var infos = face.FaceDetector(bitmap);
>         Console.WriteLine($"Face # detected {infos.Length}");
>         Console.WriteLine($"Score and Position");
>         for (int i = 0; i < infos.Length; i++)
>         {
>             Console.WriteLine($"{i}\t{infos[i].Score:f8}\t{infos[i].Location}");
>         }
>         Console.Read();
>     }
> }
> ```
> 
> }
> 
> But when I run this, I got error: Inner Exception 1: DirectoryNotFoundException: 找不到本机库目录: C:\SoccerVideos\Images\ViewFaceCoreFaceDetectForm\ViewFaceCoreFaceDetectForm\bin\Debug\net6.0-windows10.0.19041.0\viewfacecore\win\x64
> 
> I also download the repo source code (ViewFaceCore-main), and try to build it in Visual Studio 2022 (Version 17.1.1). I am using Windows 10 (Version 21H2, OS build 19044.1586) But I also got some errors, like the following: Error MSB8020 The build tools for Remote_GCC_1_0 (Platform Toolset = 'Remote_GCC_1_0') cannot be found. To build using the Remote_GCC_1_0 build tools, please install Remote_GCC_1_0 build tools. Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
> 
> Error C1083 Cannot open include file: 'seeta/FaceDetector.h': No such file or directory
> 
> Let me know how to fix this issue. PS: You can reply in Chinese, if not easy to reply in English. I think if I can install NUGET package, all necessary libraries should be OK, there should be no more errors. By the way, if there is any library which is only available in Baidu Pan, then all the people outside China can’t access. Thanks,

You need to use nuget to install ViewFaceCore.runtime.win.vc and ViewFaceCore.all_models, and it can only run on X86, it is not stable under X64

**Comment by asdRain** [comment]
X64 求Fix

**Comment by withsalt** [comment]
fixed
