### ISSUE TITLE
X64运行不起来,报错期待更新

### ISSUE THREAD

**Issue by shouhujishu** [ViewFaceCore/ViewFaceCore#39]
跑十几次就会报错,如下问题 期待作者更新
托管调试助手 "FatalExecutionEngineError"
运行时遇到了错误。此错误的地址为 0x1f6a7a22，在线程 0x55a0 上。错误代码为 0xc0000005。此错误可能是 CLR 中的 bug，或者是用户代码的不安全部分或不可验证部分中的 bug。此 bug 的常见来源包括用户对 COM-interop 或 PInvoke 的封送处理错误，这些错误可能会损坏堆栈。

**Comment by masgh21** [comment]
Hello
I have same Error ,
can you solve it ?
@shouhujishu

**Comment by shouhujishu** [comment]
> Hello I have same Error , can you solve it ? @shouhujishu

Change the x86 version

**Comment by masgh21** [comment]
thanks @shouhujishu 
can you help me
for test viewface with asp.net on server ??
i got this Error .
[This link](https://github.com/ViewFaceCore/ViewFaceCore/issues/41)

**Comment by withsalt** [comment]
@masgh21 fixed
@shouhujishu 已处理

**Comment by shouhujishu** [comment]
> @masgh21 fixed @shouhujishu 已处理

没有查询到有版本发布?

**Comment by View12138** [comment]
现已发布 !
