### ISSUE TITLE
System.IO.DirectoryNotFoundException: 找不到本机库目录: c:\windows\system32\inetsrv\viewfacecore\win\x64

### ISSUE THREAD

**Issue by masgh21** [ViewFaceCore/ViewFaceCore#40]
I use viewfaceCore in asp.net application and it works on local But 
when I Published My app and  uploaded it to server and it gave this error .

System.IO.DirectoryNotFoundException: 找不到本机库目录: c:\windows\system32\inetsrv\viewfacecore\win\x64

I go to this path 

c:\windows\system32\inetsrv\viewfacecore\win\x64
and copy files there .

But it does not solve .

My photo Attach .

 
![photo_2022-04-30_14-52-46](https://user-images.githubusercontent.com/90691672/166101734-5da57886-1056-4d5f-8a80-e1cb1dc3af5e.jpg)

<img width="606" alt="image_2022-04-30_14-48-53" src="https://user-images.githubusercontent.com/90691672/166101630-8ba8df8d-f7f8-4634-b704-561e5fe0d150.png">

**Comment by withsalt** [comment]
fixed
