### ISSUE TITLE
Asp.net Unable to load DLL 'ViewFaceBridge': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

### ISSUE THREAD

**Issue by masgh21** [ViewFaceCore/ViewFaceCore#41]
i upload my asp.net to server 
i got this error ,

Unable to load DLL 'ViewFaceBridge': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)

anyone can help ?

**Comment by gornear** [comment]
Use 0.1.2 version install on nuget.org, I tested work stable.

**Comment by masgh21** [comment]
Hello @gornear 
could you test it with asp.net
On server ?

**Comment by gornear** [comment]
> Hello @gornear could you test it with asp.net On server ?

I test it on win10,  .Net 6 winform application

**Comment by masgh21** [comment]
can you share your code ?
@gornear

**Comment by masgh21** [comment]
I want to test sdk 
with asp.net 
anyone can help me ?

**Comment by View12138** [comment]
@masgh21 I'm really sorry. I've been so busy lately. Can you tell me about ViewFaceCore related packages you installed in nuget?
(实在不好意思, 最近太忙了. 可以告诉我你在 nuget 中安装的和 ViewFaceCore 相关的包吗 ?)

**Comment by masgh21** [comment]
Hello @View12138 
I installed 0.3.5 .

**Comment by View12138** [comment]
can you share your solution or simple project for me?
this is my email: ms_view@outlook.com.

**Comment by gornear** [comment]
@masgh21 leave your email, I send you the code(asp.net), I test 0.1.2 version works fine.

**Comment by withsalt** [comment]
fixed.
