### ISSUE TITLE
ViewFaceCore.all_models, ViewFaceCore.runtime.ubuntu.20.04.x64 没有License

### ISSUE THREAD

**Issue by asdRain** [ViewFaceCore/ViewFaceCore#43]
求大佬加下License文件。

**Comment by View12138** [comment]
Nuget包 ViewFaceCore.all_models >=6.0.5、ViewFaceCore.models.*  >=6.0.5、ViewFaceCore.runtime.*  >=6.0.3 已经全部加上 [SeetaFace License](https://github.com/SeetaFace6Open/index/blob/master/LICENSE)

**Comment by asdRain** [comment]
> @asdRain @ztzsws1 Nuget包 ViewFaceCore.all_models >=6.0.5 、ViewFaceCore.models.* >=6.0.5 、 ViewFaceCore.runtime.* >=6.0.3 已经全部加上 [SeetaFace License](https://github.com/SeetaFace6Open/index/blob/master/LICENSE)

跪谢
