### ISSUE TITLE
能否加入口罩检测

### ISSUE THREAD

**Issue by chhdnjut** [ViewFaceCore/ViewFaceCore#44]
我看到SeetaFace6 是有MaskDetector的，但是这个库没有口罩检测的api,目前刚好项目上要用到口罩检测。请问作者能够抽时间把口罩检测加上，不胜感激

**Comment by View12138** [comment]
设置 `FaceType = FaceType.Mask`

**Comment by chhdnjut** [comment]
> 设置 `FaceType = FaceType.Mask`

你好，我说的是口罩检测，而不是带着口罩的人脸识别呢
![image](https://user-images.githubusercontent.com/46859200/175867859-1bd9022d-5074-47bd-aca0-d69d8dae696d.png)

**Comment by View12138** [comment]
@chhdnjut 确实没有添加这个api，但是估计要好久之后才能加上了。最近时间都不多

**Comment by chhdnjut** [comment]
> @chhdnjut 确实没有添加这个api，但是估计要好久之后才能加上了。最近时间都不多

你好，我把源码下下来重新编了ViewFaceBridge和ViewFaceCore，但是在调用口罩检测的时候报如下错误
![image](https://user-images.githubusercontent.com/46859200/176109392-80a6c84a-4716-4acd-af93-cd25f39f3d42.png)
然后我去找了报错的源码
![image](https://user-images.githubusercontent.com/46859200/176109674-c8223cce-3b37-434b-ada2-1d890b38a6c5.png)
但是还是不知道问题出在哪里。请问大神有没有什么地方可以指导一下的

**Comment by View12138** [comment]
模型有安装吗 ?
> ViewFaceCore.model.mask_detector

**Comment by chhdnjut** [comment]
> 模型有安装吗 ?
> 
> > ViewFaceCore.model.mask_detector

![image](https://user-images.githubusercontent.com/46859200/176347983-e069fe8a-4fb7-4c76-8df2-3241e1b5fae9.png)
这样算安装了吗

**Comment by withsalt** [comment]
已经添加口罩识别API
