### ISSUE TITLE
Windows Server 2019 虚拟机， Run不起来

### ISSUE THREAD

**Issue by asdRain** [ViewFaceCore/ViewFaceCore#45]
<img width="1280" alt="企业微信截图_16566410503707" src="https://user-images.githubusercontent.com/15206372/176809352-f7980d5d-cc70-433a-be2d-21ceec0cfc6e.png">

**Comment by View12138** [comment]
把程序发布为 x86 的试试

**Comment by asdRain** [comment]
> 把程序发布为 x86 的试试

Tennis.dll 的问题，哈哈哈，切换成对应CPU的文件就好了
