### ISSUE TITLE
SeetaAuthorize.dll not found

### ISSUE THREAD

**Issue by asdRain** [ViewFaceCore/ViewFaceCore#46]
<img width="1280" alt="企业微信截图_16566614548035" src="https://user-images.githubusercontent.com/15206372/176848958-271f7f4f-2ff8-4318-9e9c-40b6236a3b94.png">

**Comment by View12138** [comment]
是不是没有VCRuntime？
装一下  `ViewFaceCore.runtime.win.vc` 这个包试试

**Comment by asdRain** [comment]
> 是不是没有VCRuntime？ 装一下 `ViewFaceCore.runtime.win.vc` 这个包试试

跪谢大佬
