### ISSUE TITLE
ViewFaceCore.runtime.win.vc 求Add License, 另Nuget最新版本的包，检测不道人脸信息

### ISSUE THREAD

**Issue by asdRain** [ViewFaceCore/ViewFaceCore#49]

**Comment by View12138** [comment]
- 也可以不用安装 `ViewFaceCore.runtime.win.vc` 这个包，而是直接安装 [VC++Runtime](https://docs.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170) 的包
- 检测不到人脸的问题可以看看是否有模型没有安装，或者尝试调整人脸检测阈值

**Comment by asdRain** [comment]
> * 也可以不用安装 `ViewFaceCore.runtime.win.vc` 这个包，而是直接安装 [VC++Runtime](https://docs.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170) 的包
> * 检测不到人脸的问题可以看看是否有模型没有安装，或者尝试调整人脸检测阈值

<img width="960" alt="企业微信截图_16584107598492" src="https://user-images.githubusercontent.com/15206372/180228008-ad5ff32f-476f-45b0-b247-90dc6c7e9b89.png">
