### ISSUE TITLE
增加了新的api的库要如何引用

### ISSUE THREAD

**Issue by chhdnjut** [ViewFaceCore/ViewFaceCore#50]
今天收到邮件说增加了口罩监测，但是在NuGet上的版本仍然为0.3.5，自己下了源码，但是ViewFaceBridge那里编不过，一堆奇怪的问题，我上个版本编译的时候没遇到过。能否将新版的ViewFaceBridge.dll以及ViewFaceCore.dll通过邮件发我一份。万分感谢

**Comment by View12138** [comment]
- ViewFaceCore.model.* 和 ViewFaceCore.runtime.* 已经更新到 6.0.6
- ViewFaceCore 和 ViewFaceCore.Extension 已经更新到 0.3.6

 0.3.6 之后必须要通过 ViewFaceCore.Extension.* 中的某一个来使用 ViewFaceCore

> 如果想自己编译, 可以下载对应的 nuget 包并解压可得到 相关的 *.dll 或 *.so
> 相关文档暂时还不完善, 自己编译可能有点困难

**Comment by withsalt** [comment]
链接：https://pan.baidu.com/s/1KYldvqf7fC94ciV1pnDOlg?pwd=zvn6 
提取码：zvn6 
放到src\SeetaFace\index下面

**Comment by chhdnjut** [comment]
问题解决，感谢作者
