### ISSUE TITLE
[Bug]CompareByCroppedFace返回的值为一个非数字 -nan

### ISSUE THREAD

**Issue by liangbaikaizzzZZZ** [ViewFaceCore/ViewFaceCore#51]
#include "seeta/FaceDetector.h"
#include "seeta/FaceLandmarker.h"
#include "seeta/FaceDatabase.h"
#include "seeta/FaceRecognizer.h"
#include "seeta/Struct_cv.h"

#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <iostream>
#include <chrono>

int main() {
    
    seeta::ModelSetting FRsetting;
    seeta::ModelSetting FDsetting;
    seeta::ModelSetting FLsetting;

    FRsetting.set_device(SEETA_DEVICE_GPU);
    FRsetting.set_id(0);
    FRsetting.append("./models/face_recognizer.csta");

    FDsetting.set_device(SEETA_DEVICE_GPU);
    FDsetting.set_id(0);
    FDsetting.append("./models/face_detector.csta");

    FLsetting.set_device(SEETA_DEVICE_GPU);
    FLsetting.set_id(0);
    FLsetting.append("./models/face_landmarker_pts5.csta");

    seeta::FaceDatabase     FDB_gpu(FRsetting);
    seeta::FaceDetector     FD_gpu(FDsetting);
    seeta::FaceLandmarker   FL_gpu(FLsetting);

  
    seeta::cv::ImageData image1 = cv::imread("./img/huge.jpg");
    seeta::cv::ImageData image2 = cv::imread("./img/liuyifei.jpg");

    std::cout << "Got image: [" << image1.width << ", " << image1.height << ", " << image1.channels << "]" << std::endl;

        seeta::cv::ImageData facedate1(FDB_gpu.GetCropFaceWidthV2(),FDB_gpu.GetCropFaceHeightV2(),FDB_gpu.GetCropFaceChannelsV2());
        seeta::cv::ImageData facedate2(FDB_gpu.GetCropFaceWidthV2(),FDB_gpu.GetCropFaceHeightV2(),FDB_gpu.GetCropFaceChannelsV2());

        auto faces1 = FD_gpu.detect(image1);
        auto points1 = FL_gpu.mark(image1,faces1.data[0].pos);
        FDB_gpu.CropFaceV2(image1,points1.data(),facedate1);

        auto faces2 = FD_gpu.detect(image2);
        auto points2 = FL_gpu.mark(image2,faces2.data[0].pos);
        FDB_gpu.CropFaceV2(image2,points2.data(),facedate2);

        cv::imwrite("./img/test1.jpg", seeta::cv::ImageData(facedate1).toMat());
        cv::imwrite("./img/test2.jpg", seeta::cv::ImageData(facedate2).toMat());

        float score1 = FDB_gpu.CompareByCroppedFace(facedate1,facedate2);
 
        std::cout << "score: " << score1 << std::endl;

    return 0;
}

结果为：score: -nan

**Comment by liangbaikaizzzZZZ** [comment]
找到原因了  CropFaceV2 这个接口有BUG

**Comment by withsalt** [comment]
建议提给：https://github.com/seetafaceengine/SeetaFace6/issues
虽然大概率他们也不会处理就是了....
