### ISSUE TITLE
[Bug]不能有中文路径吗

### ISSUE THREAD

**Issue by duyanSD** [ViewFaceCore/ViewFaceCore#52]
**简明描述**
运行程序目录如果是中文路径，实例化ViewFaceCore.Core.FaceDetector 会报异常,

**开发环境**
 目标框架: [net471]
 项目类型 [ Windows窗体应用]

**相关包清单**
  [ViewFaceCore 0.3.6]
  [ViewFaceCore.model.face_recognizer_mask 6.0.6]

![image](https://user-images.githubusercontent.com/110367812/184058768-56e1b893-ad5d-437e-9c06-e01dfc8351ac.png)

**Comment by withsalt** [comment]
是的，不能有中文路径。

**Comment by duyanSD** [comment]
好的，谢谢，能支持中文路径就更好了

**Comment by withsalt** [comment]
dev分支已解决中文路径问题。下个版本发布后将支持中文路径

**Comment by duyanSD** [comment]
谢谢
