### ISSUE TITLE
[Bug]Unable to load DLL 'ViewFaceBridge' or one of its dependencies

### ISSUE THREAD

**Issue by MartinKoo** [ViewFaceCore/ViewFaceCore#53]
**重现步骤**

1. 新建一个.NET Standard 2.0类库(Any CPU)，假设项目名为 HelloWorld.FaceService。通过NuGet安装如下包：
- ViewFaceCore (0.3.6)
- ViewFaceCore.Extension.SkiaSharp (0.3.6)
- ViewFaceCore.model.face_detector (6.0.6)
- ViewFaceCore.model.face_landmarker_pts5 (6.0.6)
- ViewFaceCore.model.face_recognizer_light (6.0.6)
- ViewFaceCore.runtime.win.x64 (6.0.6)
- ViewFaceCore.runtime.win.x86 (6.0.6)
此项目主要是对 ViewFaceCore 进行封装，提供诸如”根据图片获取人脸特征，再跟人脸库的数据进行比对，找出对应的人“之类的功能。

2. 新建一个.NET Core 2.2 WebAPI项目(Any CPU)，假设项目名为 HelloWorld.FaceWebAPI。其引用了上面那个类库。
此项目主要是作为应用程序的后端，提供一系列的API给前端访问。

3. 此时进行调试，会出现大意为找不到ViewFaceCore.dll的异常。将.nuget\packages\viewfacecore\0.3.6\lib\netstandard2.0\ViewFaceCore.dll拷贝到HelloWorld.FaceWebAPI\bin\Debug目录也不行。

4. 在HelloWorld.FaceWebAPI项目，通过NuGet安装如下包：
- ViewFaceCore (0.3.6)
- ViewFaceCore.Extension.SkiaSharp (0.3.6)

5. 此时进行调试，会出现”Not found library path.“的异常。

6. 把HelloWorld.FaceService\bin\Debug\netstandard2.0\viewfacecore文件夹拷贝到HelloWorld.FaceWebAPI\bin\Debug\netcoreapp2.2目录，**此时进行调试，功能正常**了。

7. 把HelloWorld.FaceWebAPI项目发布一份到bin\Release\netcoreapp2.2\publish，并将bin\Debug\netcoreapp2.2\viewfacecore文件夹拷贝一份到bin\Release\netcoreapp2.2\publish

8. 将HelloWorld.FaceWebAPI\bin\Release\netcoreapp2.2\publish目录的所有文件(含子文件夹），拷贝、部署到另一台机器的 IIS 上。

9. 此时前端访问API，就出现了题目所示的异常：Unable to load DLL 'ViewFaceBridge' or one of its dependencies

**为什么本机调试没问题了，部署到另一台机器上还不行呢？**

**开发环境**
 - 目标框架: [.netcoreapp2.2]
 - 项目类型: [ASP.NET Core API]

**运行环境**
 - 操作系统: [Windows 2012 专业版]
 - 系统类型: [64 位操作系统, 基于 x64 的处理器]

**附件**

**Comment by withsalt** [comment]
尝试将
ViewFaceCore.model.face_detector (6.0.6)
ViewFaceCore.model.face_landmarker_pts5 (6.0.6)
ViewFaceCore.model.face_recognizer_light (6.0.6)
ViewFaceCore.runtime.win.x64 (6.0.6)
ViewFaceCore.runtime.win.x86 (6.0.6)
安装到HelloWorld.FaceWebAPI项目。

**Comment by MartinKoo** [comment]
> 尝试将 ViewFaceCore.model.face_detector (6.0.6) ViewFaceCore.model.face_landmarker_pts5 (6.0.6) ViewFaceCore.model.face_recognizer_light (6.0.6) ViewFaceCore.runtime.win.x64 (6.0.6) ViewFaceCore.runtime.win.x86 (6.0.6) 安装到HelloWorld.FaceWebAPI项目。

  试了，不行，还是一样的错误：Unable to load DLL 'ViewFaceBridge' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)

**Comment by withsalt** [comment]
请问是测试项目吗？方便打个包传上来我们分析下吗？

**Comment by View12138** [comment]
@MartinKoo 我按照你的 1,2 步骤进行了尝试, 得到的结果是正确的. 使用的是VS2022 Preview. 
你的开发工具是哪个版本? 我觉得可能是 nuget 客户端的问题. 
[测试项目地址](https://github.com/View12138/HelloWorld.FaceService)

**Comment by MartinKoo** [comment]
@View12138 VS2019。我跟踪到的异常信息：
![image](https://user-images.githubusercontent.com/111052640/184320356-aeff038e-e1df-42ae-9e05-7aef6ca0d7ce.png)

**Comment by MartinKoo** [comment]
> @View12138 VS2019。我跟踪到的异常信息： ![image](https://user-images.githubusercontent.com/111052640/184320356-aeff038e-e1df-42ae-9e05-7aef6ca0d7ce.png)

这个忽略掉，原因是我本机的bin\Debug\netcoreapp2.2\viewfacecore\win\x64里面空的，把所需文件拷贝进去，运行ok了。
但是部署到另一台机器上还是不行。
输出的异常堆栈为：
![1660297178431](https://user-images.githubusercontent.com/111052640/184328403-f6291bc9-e39b-49c9-a93e-cd11f11f60a7.jpg)

**Comment by withsalt** [comment]
@MartinKoo @View12138 
按照步骤1,2同样没有复现，有点怀疑是nuget包没有下面。检查一下HelloWorld.FaceWebAPI\bin\Debug\netcoreapp2.1目录下面的viewfacecore文件夹里面是不是有内容。还有就是检查一下包版本是否正确。

**Comment by MartinKoo** [comment]
难搞！
我又找了台机器，同样的文件，在这台机器部署又没问题。
这下不知道该怎么排查了。。。

**Comment by View12138** [comment]
@MartinKoo 要不尝试安装一下 `ViewFaceCore.runtime.win.vc` ?

**Comment by MartinKoo** [comment]
@withsalt @View12138 我把代码上传到[repo](https://github.com/MartinKoo/HelloWorld.Face)了，如果有空的话，请试一试。

**Comment by MartinKoo** [comment]
> @MartinKoo 要不尝试安装一下 `ViewFaceCore.runtime.win.vc` ?

@withsalt @View12138 问题已解决，把这个包安装上就可以了！

**Comment by lovemory** [comment]
我也碰到这样的错误：
System.lIlNotFoundException: Unable to load DLL "ViewFaceBridge' or one of its dependencies:找不到指定的模块。(0x8007007E)

机器是苹果的， 操作是windows.    "ViewFaceCore.runtime.win.vc" 也是没有安装

环境信息：


处理器	Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz   2.30 GHz
机带 RAM	16.0 GB (15.9 GB 可用)
设备 ID	17A635B7-D40D-49BE-83B7-D0C0731A6135
产品 ID	00328-10000-00001-AA220
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入


版本	Windows 10 教育版
版本号	20H2
安装日期	‎2019/‎12/‎7
操作系统内部版本	19042.2006
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by withsalt** [comment]
> 我也碰到这样的错误： System.lIlNotFoundException: Unable to load DLL "ViewFaceBridge' or one of its dependencies:找不到指定的模块。(0x8007007E)
> 
> 机器是苹果的， 操作是windows. "ViewFaceCore.runtime.win.vc" 也是没有安装
> 
> 环境信息：
> 
> 处理器 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz 2.30 GHz 机带 RAM 16.0 GB (15.9 GB 可用) 设备 ID 17A635B7-D40D-49BE-83B7-D0C0731A6135 产品 ID 00328-10000-00001-AA220 系统类型 64 位操作系统, 基于 x64 的处理器 笔和触控 没有可用于此显示器的笔或触控输入
> 
> 版本 Windows 10 教育版 版本号 20H2 安装日期 ‎2019/‎12/‎7 操作系统内部版本 19042.2006 体验 Windows Feature Experience Pack 120.2212.4180.0

能贴下你的代码吗？还有就是可以尝试安装一下ViewFaceCore.runtime.win.vc
