### ISSUE TITLE
[Bug]ViewFaceCore.Native.ViewFaceNative 异常

### ISSUE THREAD

**Issue by ertu426** [ViewFaceCore/ViewFaceCore#56]
**简明描述**
我使用 dotnet 6 web api 创建了一个项目 并使用了 该包。
我把它编程成 docker 容器 并启动起来
但 会提示

> [06:30:00 WRN] System.TypeInitializationException: The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.
> System.IO.FileNotFoundException: Can not found library /app/viewfacecore/linux/arm64/libtennis_haswell.so.

**开发环境**
 - 目标框架: dotnet 6 arm64
 - 项目类型 ASP.NET Core API

**相关包清单**
 - ViewFaceCore 0.3.7
 - ViewFaceCore.all_models 6.0.7
 - ViewFaceCore.Extension.System 0.3.7
 - ViewFaceCore.runtime.linux.arm 6.0.7
 - ViewFaceCore.runtime.linux.arm64 6.0.7
 - ViewFaceCore.runtime.ubuntu.20.04.x64 6.0.7
 - ViewFaceCore.runtime.win.vc 6.0.0
 - ViewFaceCore.runtime.win.x64 6.0.7
 - ViewFaceCore.runtime.win.x86 6.0.7

**运行环境**
 - 操作系统: Ubuntu 22.04.1 LTS
 - 系统类型: aarch64

**附件**
<details><summary>日志片段  LD_DEBUG=libs</summary>
         1:    find library=libgdiplus.so.so [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/libgdiplus.so.so
         1:      trying file=/usr/lib/aarch64-linux-gnu/libgdiplus.so.so
         1:      trying file=/lib/libgdiplus.so.so
         1:      trying file=/usr/lib/libgdiplus.so.so
         1:
         1:    find library=liblibgdiplus.so.so [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/liblibgdiplus.so.so
         1:      trying file=/usr/lib/aarch64-linux-gnu/liblibgdiplus.so.so
         1:      trying file=/lib/liblibgdiplus.so.so
         1:      trying file=/usr/lib/liblibgdiplus.so.so
         1:
         1:    find library=libgdiplus.so [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/libgdiplus.so
         1:
         1:    find library=libglib-2.0.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libglib-2.0.so.0
         1:
         1:    find library=libcairo.so.2 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libcairo.so.2
         1:
         1:    find library=libfreetype.so.6 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libfreetype.so.6
         1:
         1:    find library=libjpeg.so.8 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libjpeg.so.8
         1:
         1:    find library=libtiff.so.5 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libtiff.so.5
         1:
         1:    find library=libgif.so.7 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libgif.so.7
         1:
         1:    find library=libpng16.so.16 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libpng16.so.16
         1:
         1:    find library=libX11.so.6 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libX11.so.6
         1:
         1:    find library=libexif.so.12 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libexif.so.12
         1:
         1:    find library=libfontconfig.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libfontconfig.so.1
         1:
         1:    find library=libpcre.so.3 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libpcre.so.3
         1:
         1:    find library=libpixman-1.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libpixman-1.so.0
         1:
         1:    find library=libxcb-shm.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libxcb-shm.so.0
         1:
         1:    find library=libxcb.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libxcb.so.1
         1:
         1:    find library=libxcb-render.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libxcb-render.so.0
         1:
         1:    find library=libXrender.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libXrender.so.1
         1:
         1:    find library=libXext.so.6 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libXext.so.6
         1:
         1:    find library=libz.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libz.so.1
         1:
         1:    find library=libbrotlidec.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libbrotlidec.so.1
         1:
         1:    find library=libwebp.so.7 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libwebp.so.7
         1:
         1:    find library=libzstd.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libzstd.so.1
         1:
         1:    find library=liblzma.so.5 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/liblzma.so.5
         1:
         1:    find library=libjbig.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libjbig.so.0
         1:
         1:    find library=libdeflate.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libdeflate.so.0
         1:
         1:    find library=libexpat.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libexpat.so.1
         1:
         1:    find library=libuuid.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libuuid.so.1
         1:
         1:    find library=libXau.so.6 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libXau.so.6
         1:
         1:    find library=libXdmcp.so.6 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libXdmcp.so.6
         1:
         1:    find library=libbrotlicommon.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libbrotlicommon.so.1
         1:
         1:    find library=libbsd.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libbsd.so.0
         1:
         1:    find library=libmd.so.0 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libmd.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libmd.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libbsd.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libbrotlicommon.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libXdmcp.so.6
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libXau.so.6
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libuuid.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libexpat.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libdeflate.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libjbig.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/liblzma.so.5
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libzstd.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libwebp.so.7
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libbrotlidec.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libz.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libxcb.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libX11.so.6
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libXext.so.6
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libXrender.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libxcb-render.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libxcb-shm.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libpixman-1.so.0
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libpcre.so.3
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libpng16.so.16
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libfreetype.so.6
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libfontconfig.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libexif.so.12
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libgif.so.7
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libjpeg.so.8
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libtiff.so.5
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libcairo.so.2
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libglib-2.0.so.0
         1:
         1:
         1:    calling init: /lib/libgdiplus.so
         1:
         1:    find library=libgdiplus.so.so [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/libgdiplus.so.so
         1:      trying file=/usr/lib/aarch64-linux-gnu/libgdiplus.so.so
         1:      trying file=/lib/libgdiplus.so.so
         1:      trying file=/usr/lib/libgdiplus.so.so
         1:
         1:    find library=liblibgdiplus.so.so [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/liblibgdiplus.so.so
         1:      trying file=/usr/lib/aarch64-linux-gnu/liblibgdiplus.so.so
         1:      trying file=/lib/liblibgdiplus.so.so
         1:      trying file=/usr/lib/liblibgdiplus.so.so
         1:
         1:
         1:    calling init: /app/viewfacecore/linux/arm64/libSeetaAuthorize.so
         1:
         1:    find library=libgomp.so.1 [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:      trying file=/lib/aarch64-linux-gnu/libgomp.so.1
         1:
         1:
         1:    calling init: /lib/aarch64-linux-gnu/libgomp.so.1
         1:
         1:
         1:    calling init: /app/viewfacecore/linux/arm64/libtennis.so
         1:
         1:    find library=Microsoft.DiaSymReader.Native.arm64.dll [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:
         1:    find library=Microsoft.DiaSymReader.Native.arm64.dll [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:
         1:    find library=Microsoft.DiaSymReader.Native.arm64.dll [0]; searching
         1:     search cache=/etc/ld.so.cache
         1:     search path=/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/lib:/usr/lib            (system search path)
         1:      trying file=/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/aarch64-linux-gnu/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:      trying file=/usr/lib/Microsoft.DiaSymReader.Native.arm64.dll
         1:
[06:30:00 WRN] System.TypeInitializationException: The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.
 ---> System.IO.FileNotFoundException: Can not found library /app/viewfacecore/linux/arm64/libtennis_haswell.so.
   at ViewFaceCore.Native.ViewFaceNative..cctor()
   --- End of inner exception stack trace ---
   at ViewFaceCore.Native.ViewFaceNative.GetFaceDetectorHandler(Double faceSize, Double threshold, Double maxWidth, Double maxHeight, Int32 deviceType)
   at ViewFaceCore.Core.FaceDetector..ctor(FaceDetectConfig config)
</details>

<details><summary>代码片段</summary>
    public static async Task<List<float>> GetFaceInfo(string image)
    {
        // Base64 转 Bitmap
        byte[] arr = Convert.FromBase64String(image);
        MemoryStream ms = new MemoryStream(arr);
        Bitmap bmp = new Bitmap(ms);

        using FaceDetector faceDetector = new FaceDetector();
        using FaceLandmarker faceMark = new FaceLandmarker();
        using FaceRecognizer faceRecognizer = new FaceRecognizer();

        Stopwatch sw = Stopwatch.StartNew();
        var result = faceRecognizer.Extract(bmp, GetFaceMarkPoint(faceDetector, faceMark, bmp)).ToList();
        sw.Stop();

        return result;
    }

    private static FaceMarkPoint[] GetFaceMarkPoint(FaceDetector faceDetector, FaceLandmarker faceMark, object bitmap)
    {
        var infos = faceDetector.Detect(bitmap);
        var info = infos.First();
        return faceMark.Mark(bitmap, info);
    }
</details>

**Comment by withsalt** [comment]
fixed. 安装最新ViewFaceCore nuget包（0.3.8）

**Comment by withsalt** [comment]
顺便请问下您在arm64平台，这个库效率如何？

**Comment by ertu426** [comment]
好的  我就是自己做做一个小功能  没有具体测试效率  不过对我来说够用了
